version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    groups:
      maven-all:
        patterns:
          - '*'
    ignore:
      - dependency-name: berlin.yuna:nats-server

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 1
    groups:
      actions-all:
        patterns:
          - '*'
