name: "MVN_RELEASE"

on:
  workflow_dispatch:
    branches: [ main, master ]
  schedule:
    - cron: "0 10 * * *"

jobs:
  maven_update:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_update.yml@main
    # has_pom                     ${{needs.maven_update.outputs.has_pom}}
    # has_changes                 ${{needs.maven_update.outputs.has_changes}}
    # java_version                ${{needs.maven_update.outputs.java_version}}
    # project_version             ${{needs.maven_update.outputs.project_version}}
  maven_test:
    needs: "maven_update"
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_test.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # has_changes                 ${{needs.maven_test.outputs.has_changes}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # project_version             ${{needs.maven_test.outputs.project_version}}
    # has_publish_to_code_climate ${{needs.maven_test.outputs.has_publish_to_code_climate}}
  maven_tag:
    needs: maven_test
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_tag.yml@main
    with:
      semver_strategy: rc
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # new_version                 ${{needs.maven_test.outputs.new_version}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # project_version             ${{needs.maven_test.outputs.project_version}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
    # has_publish_to_code_climate ${{needs.maven_test.outputs.has_publish_to_code_climate}}
  maven_github_release:
    needs: maven_tag
    if: needs.maven_tag.outputs.semver != ''
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_github_release.yml@main
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # changelog                   ${{needs.maven_test.outputs.changelog}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
    # latest_tag                  ${{needs.maven_test.outputs.latest_tag}}
    # second_latest_tag           ${{needs.maven_test.outputs.second_latest_tag}}
    # semver_strategy             ${{needs.maven_test.outputs.semver_strategy}}
  maven_central_release:
    needs: maven_tag
    if: needs.maven_tag.outputs.semver != ''
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@main
    secrets:
      GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      OSSH_USER: ${{secrets.OSSH_USER}}
      OSSH_PASS: ${{secrets.OSSH_PASS}}
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
