name: 🧪 CI · Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        default: ''
        type: string

permissions: {}

concurrency:
  group: build-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build_common.yml@81f3937399028513b70b4258e032ac856768dbfd
    with:
      ref: ${{ inputs.ref || github.sha }}
