name: "Central"

permissions: {}

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: "Existing git tag to publish to Maven Central"

jobs:
  maven_central:
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_maven_central.yml@main
    with:
      version: ${{ inputs.version }}
    secrets: inherit
