name: 🛠️ CI · Maintenance

on:
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run.
        required: true
        default: true
        type: boolean

permissions: {}

jobs:
  maven_wrapper:
    permissions:
      actions: write
      contents: write
      pull-requests: write
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_update_maven_wrapper.yml@93dcc244b1713aeb9594aff65df1a2901ded707f
    with:
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}

  upstream:
    permissions:
      actions: write
      contents: write
      packages: read
      pull-requests: write
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_update_upstream.yml@5b74baf9f3b43e6e4b43c249c4dd8f3bff4b739e
    with:
      upstream_repository: nats-io/nats-server
      upstream_property: nats-server.version
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
