name: "MANUAL_CENTRAL_RELEASE"

on:
  workflow_dispatch:
    branches: [ main, master ]

jobs:
  maven_central_release:
    name: "maven"
    uses: YunaBraska/YunaBraska/.github/workflows/wc_maven_central_release.yml@main
    secrets:
      GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      OSSH_USER: ${{secrets.OSSH_USER}}
      OSSH_PASS: ${{secrets.OSSH_PASS}}
    # has_pom                     ${{needs.maven_test.outputs.has_pom}}
    # java_version                ${{needs.maven_test.outputs.java_version}}
