name: "On Push"

on:
  push:
    branches-ignore:
      - main
      - master
      - default

jobs:
  builld:
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build.yml@main
    with:
      ref: ${{ github.ref_name }}
      run_update: false  # Updates only on main branches
      run_test: true     # Always run tests
      run_deploy: disabled  # Never deploy on non-main branches
    secrets: inherit
